CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.dim_admission_type (
    admission_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_type_description TEXT NOT NULL UNIQUE
);