CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.dim_admission_source (
    admission_source_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admission_source_description TEXT NOT NULL UNIQUE
);