CREATE SCHEMA IF NOT EXISTS analytics;

CREATE TABLE IF NOT EXISTS analytics.dim_discharge_disposition (
    discharge_disposition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discharge_disposition_description TEXT NOT NULL UNIQUE
);